# Site settings
title:
  en: -CIFRE-
  fr: -CIFRE-
  it: -CIFRE-
  pt: -CIFRE-
  sp: -CIFRE-
email: cifre.olomouc@upol.cz
remote_theme: romanistika-upol/template1
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
images:
  logo: ./assets/img/logo.png 
  banner: ./assets/img/banner.jpg
event:
  address: "Filozofická fakulta<br>Univerzita Palackého v Olomouci<br>Křížkovského 511/10<br>771 48 Olomouc<br>"
  dates: April 11-13, 2019
  title: CIFRE 2019 - II International Colloquium of Romance Philologies for Students
# Build settings
markdown: kramdown
